config/routes.rb
BID::Application.routes.draw do

  resources :locations

  resources :attendees

  devise_for :users
  root 'pages#home'

  

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  validates_presence_of :name, :email, :attendees, :zip
  validates_uniqueness_of :email, message: "has already been registered for this event. If you want to change your RSVP, please email davidandnancy.grant@mountainschool.org"

  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :city_name
  
  has_many :attendees

  geocoded_by :city_name
  after_validation :geocode

  acts_as_gmappable

  def gmaps4rails_address
    "#{self.city_name}"
  end

  def gmaps4rails_infowindow
    "#{self.city_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  if Rails.env.production?
    devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]
  before_action :authorize, :except => [:new, :create]

  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
  end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(attendee_params)

    respond_to do |format|
      if @attendee.save
        UserMailer.attendee_confirmation(@attendee).deliver
        UserMailer.admin_notification(@attendee).deliver
        format.html { redirect_to root_path, notice: 'Great, we have your info.  Expect an email from us shortly.' }
        format.json { render action: 'show', status: :created, location: @attendee }
      else
        format.html { render action: 'new' }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: 'attendee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url }
      format.json { head :no_content }
    end
  end

  private
    def authorize
      redirect_to root_path unless current_user
      flash[:notice] = "You need to be logged in to see these pages." unless current_user
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:name, :semester_season, :semester_year, :location_id, :phone, :email, :attendees, :host, :zip, :follow_up, :virtual)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :headcount, only: [:index]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city_name, :host_name, :address, :description, :latitude, :longitude, :gmaps)
    end

    def headcount
      @headcount = Attendee.find(:all,
        :select => "location_id, count(attendees) as count",
        :group => "location_id",
        )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@attendee = Attendee.new
    locations = Location.all
    @locations_json = locations.to_gmaps4rails
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/attendees/_form.html.erb
<%= form_for @attendee, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> caused some issues:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, "Name*", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, "Email*", :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Nearest_Location, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select(:location_id, Location.order("city_name").all, :id, :city_name, :include_blank => true, :prompt => "Choose one...") %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zip, "Zip Code*", :class => 'control-label' %>
    <div class="controls">
      <%= f.phone_field :zip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :semester_season, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :semester_season, [['Fall','Fall'],['Spring','Spring']], :prompt => "Season..." %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :semester_year, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :semester_year, (1984..2013), :prompt => "Year..." %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :attendees, "Attendees*", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :attendees, (1..10) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Want_to_host?, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :host %>  YES!
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Don't see a location near you?", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :follow_up %>  I would like to know if there are enough alums in my area to form a group; please get in touch with me.
    </div>
    <div class="controls">
      <%= f.check_box :virtual %>  I would like to join a virtual, web-based video meeting on Big Idea Day. (details to follow)
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit :Submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                attendees_path, :class => 'btn' %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<%- model_class = Attendee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attendees/index.html.erb
<%- model_class = Attendee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:semester_season) %></th>
      <th><%= model_class.human_attribute_name(:semester_year) %></th>
      <th><%= model_class.human_attribute_name(:location_id) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:zip) %></th>
      <th><%= model_class.human_attribute_name(:attendees) %></th>
      <th><%= model_class.human_attribute_name(:host) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:follow_up) %></th>
      <th><%= model_class.human_attribute_name(:virtual) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= link_to attendee.name, attendee_path(attendee) %></td>
        <td><%= attendee.semester_season %></td>
        <td><%= attendee.semester_year %></td>
        <td><%= attendee.location.try(:city_name) %></td>
        <td><%= attendee.phone %></td>
        <td><%= attendee.email %></td>
        <td><%= attendee.zip %></td>
        <td><%= attendee.attendees %></td>
        <td><%= attendee.host %></td>
        <td><%=l attendee.created_at %></td>
        <td><%= attendee.follow_up %></td>
        <td><%= attendee.virtual %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_attendee_path(attendee), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      attendee_path(attendee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_attendee_path,
            :class => 'btn btn-primary' %>

app/views/attendees/new.html.erb
<%- model_class = Attendee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attendees/show.html.erb
<%- model_class = Attendee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @attendee.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:semester_season) %>:</strong></dt>
  <dd><%= @attendee.semester_season %></dd>
  <dt><strong><%= model_class.human_attribute_name(:semester_year) %>:</strong></dt>
  <dd><%= @attendee.semester_year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location_id) %>:</strong></dt>
  <dd><%= @attendee.location.try(:city_name) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @attendee.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @attendee.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zip) %>:</strong></dt>
  <dd><%= @attendee.zip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attendees) %>:</strong></dt>
  <dd><%= @attendee.attendees %></dd>
  <dt><strong><%= model_class.human_attribute_name(:follow_up) %>:</strong></dt>
  <dd><%= @attendee.follow_up %></dd>
  <dt><strong><%= model_class.human_attribute_name(:virtual) %>:</strong></dt>
  <dd><%= @attendee.virtual %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              attendees_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_attendee_path(@attendee), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              attendee_path(@attendee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_footer.html.erb
<div class="hr"><hr /></div>

<div class="container">
  <div class="row">
    <div class="span4">
      <h3>The Garden Hill Fund</h3>
      <p>
        This new program of the Mountain School Alumni Initiative will support the good work of Mountain School graduates of all ages as they bring to life the mission of the school -- to reach beyond the self and focus on the common good -- in their own communities and the larger world. <br>
      <a href="http://gardenhillfund.org" target="_blank">Learn more...</a>
      </p>
    </div>
    <div class="span4">
      <h3>Alumni Directory</h3>
      <p>
        Connect with classmates and fellow alums. Find new opportunities, learn about interesting projects or just look for a couch to crash on for a night. <br>
        <a href="https://www.mountainschool.org/podium/default.aspx?t=136798" target="_blank">Connect now...</a>
      </p>
    </div>
    <div class="span4 social-buttons">
      <h3>Get Social!</h3>
        <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FThe-Mountain-School-of-Milton-Academy%2F252084468164123%3Fref%3Dbr_tf&amp;width=250&amp;height=35&amp;colorscheme=light&amp;layout=standard&amp;action=like&amp;show_faces=false&amp;send=false&amp;appId=393264994062050" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:250px; height:35px;" allowTransparency="true"></iframe>
        <br><br>

        <a href="https://twitter.com/MountainSchool" class="twitter-follow-button" data-show-count="false">Follow @MountainSchool</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
        </script><br>

        <a href="http://www.linkedin.com/groups?gid=150431&trk=group-name" target="_blank"><%= image_tag("/images/linkedin.png", :height => '75', :width => '160', :alt => "TMS Alumni Site") %></a><br>
    </div>
  </div>
</div>
<% if current_user %>
  <%= link_to "Home", root_path %> | 
  <%= link_to "Attendees", attendees_path %> | 
  <%= link_to "Locations", locations_path %> | 
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

<%= yield :scripts %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <li class="active brand">
          <%= link_to "Big Idea Day", root_path %>
        </li>
        <li><a href="/#sign-up-form">Sign Up</a></li>
        <li><a href="/#about-details">Learn More</a></li>
        <li><a href="/#resources">Resources</a></li>
      </ul>
      <ul class="nav pull-right">
        <li>
          <a href="https://www.mountainschool.org/podium/default.aspx", target="_blank"><%= image_tag("/images/TMS_Logo.png", :height => '49.6', :width => '110.4', :alt => "TMS Alumni Site") %></a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Big Idea Day 2013 | The Mountain School</title>
  <meta name="description" content="The Mountain School Big Idea Day 2013">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render 'layouts/header' %>

<%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :city_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :host_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :host_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gmaps, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :gmaps, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                locations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/index.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:city_name) %></th>
      <th>Sign Ups</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.city_name, location_path(location) %></td>
        <td>
          <% @headcount.each do |headcount| %>
            <% if headcount.location_id == location.id %>
              <%= headcount.count %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_location_path(location), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      location_path(location),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_location_path,
            :class => 'btn btn-primary' %>

app/views/locations/new.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/show.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:city_name) %>:</strong></dt>
  <dd><%= @location.city_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:host_name) %>:</strong></dt>
  <dd><%= @location.host_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @location.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @location.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @location.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @location.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gmaps) %>:</strong></dt>
  <dd><%= @location.gmaps %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              locations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_location_path(@location), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              location_path(@location),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/pages/home.html.erb
<!-- <h1>2013 Big Idea Day - October 5th, 2013</h1>
<h2>Brought to you by The Mountain School </h2> -->

<div id="buckets-container">
  <%= image_tag("/images/cows.png", :alt => "Garden Hill", :id => "buckets-image") %>
  <p id="buckets-text">
    Big Idea Day - October 5th, 2013
  </p>
</div>

<div id="topic">
  <h1>Gender in America in 2013: Where are we now?</h1>
</div>

<div id="about-summary">
	Join 5-10 Mountain School alums who live near you for a Big Idea Day discussion at a volunteer host’s home on the afternoon of <b>Saturday, October 5th</b>.  Just let us know you want to participate by signing up below, and we will match you with the nearest host.  If you are interested in hosting yourselves, you can indicate that as well; we still need a few more gathering places.
	<br>
	If you do not live near other Mountain School graduates, please let us know if you would like to participate in a virtual meeting via the Internet.
</div><br>

<div class="hr"><hr /></div>

<div class="container" id="sign-up-section">
  <div class="row">
    <div class="span5">
      <div id="sign-up-form">
        <h2>Sign Up</h2>
        <h6>Fields with an * are required</h6>

        <%= render 'attendees/form' %>
      </div>
    </div>
    <div class="span7">
      <% if false %>
        <img src="http://maps.googleapis.com/maps/api/staticmap?center=Vershire,Vermont&zoom=13&size=400x300&maptype=terrain&sensor=false">
      <% end %>

      <%= gmaps4rails(@locations_json) %>

    </div>
  </div>

  <div class="hr"><hr /></div>
</div>

<div id="about-details">
  <h2>Some Questions to Consider</h2>
  Last year’s inaugural Big Idea Day discussion, Technology: Who’s the Boss? was a huge success (and led to coverage in The New York Times and on the BBC, as well as influenced the new cell phone policy at The Mountain School). This year, after conferring with graduates at Reunions, the Committee has chosen the topic of gender, and we will pose questions such as:
  <br>

  <ul>
    <li>How has gender affected your own choices in life, and how does it affect your sense of the future?</li>
    <li>Do people in their twenties think differently about gender than those in their thirties, forties, and older?  How?</li>
    <li>What is the relationship between gender and money?</li>
    <li>Have the writings of Ann Marie Slaughter and Sheryl Sandberg (and others) on the work/life balance of women in the workplace affected your own interactions or behavior at work, or at home?</li>
    <li>Are men included in this debate? What are the ways in which it is challenging to be a man in today's changing culture, society, and economy? And for that matter, what does it mean to be "a man?"</li>
  </ul><br>

  And since we like to tie Big Idea Day back to The Mountain School:
  <ul>
    <li>Why is it that applications to The Mountain School from girls have consistently outnumbered those from boys by two-(or even three-)to-one?  Should the Mountain School do something different to achieve gender balance, and if so what?  Or should they “leave well enough alone?”</li>
    <li>What did the Mountain School teach you, directly or indirectly, about gender?  What should it teach its current students, and how?</li>
  </ul>
</div>

<div class="hr"><hr /></div>

<div id="resources">
  <h2>Resources to get you thinking</h2>
  <h4>Coming soon to everyone who signs up.</h4>
</div>